apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: e5xq3o60z-java-quarkus
  janus-idp.io/tekton: e5xq3o60z-java-quarkus
  backstage.io/kubernetes-id: e5xq3o60z-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: e5xq3o60z-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
